version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./base.dockerfile
    image: ${COMPOSE_PROJECT_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}
    hostname: ${COMPOSE_PROJECT_NAME}
    networks:
      - default
    ports:
      - "8000:8000"
    working_dir: "/home/rootless/src"
    tty: true
    volumes:
      - ../src:/home/rootless/src

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge
